### ISSUE TITLE
Не удалось запустить sdk

### ISSUE THREAD

**Issue by Starmel** [TinkoffCreditSystems/tinkoff-asdk-android#13]
java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.myrequest.c1/ru.tinkoff.acquiring.sdk.PayFormActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                      at ru.tinkoff.acquiring.sdk.PayFormActivity.onCreate(PayFormActivity.java:125)
                      at android.app.Activity.performCreate(Activity.java:6682)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6121) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 

java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.myrequest.c1/ru.tinkoff.acquiring.sdk.PayFormActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
                      at android.content.res.Resources.getText(Resources.java:335)
                      at android.content.res.Resources.getString(Resources.java:381)
                      at ru.tinkoff.acquiring.sdk.PayFormActivity.onCreate(PayFormActivity.java:129)
                      at android.app.Activity.performCreate(Activity.java:6682)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6121) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by tralfamadore** [comment]
> android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
Такая ошибка будет возникать, если тема использованная для PayFormActivity не содержит Toolbar. 

> android.content.res.Resources$NotFoundException: String resource ID #0x0
Эта ошибка будет возникать, если тема использованная для PayFormActivity не содержит атрибут acqPayFormTitle

Для более легкой интеграции я бы посоветовал указать AcquiringTheme в качестве parent для темы используемой для PayFormActivity, и переопределять стили и атрибуты по мере необходимости. Описание стилей можно обнаружить [здесь](https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/wiki/Styles).
