### ISSUE TITLE
Не запускается PayFormActivity

### ISSUE THREAD

**Issue by domr** [TinkoffCreditSystems/tinkoff-asdk-android#14]
Версия 1.2.0
Падает при старте PayFormActivity с исключением java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
Публичный ключ из настроек тестового терминала на https://oplata.tinkoff.ru/lk2
С параметрами из sample всё работает.

**Дополнено**: заметил, что публичный ключ, полученный на https://oplata.tinkoff.ru/lk2 длиной всего 65 симовлов, хотя по префиксу видно, что это 2048-битный RSA, и должен быть намного длиннее. (тестовый ключ из sample как раз выглядит, как настоящий)

`java.lang.RuntimeException: Unable to start activity ComponentInfo{***/ru.tinkoff.acquiring.sdk.PayFormActivity}: ru.tinkoff.acquiring.sdk.AcquiringSdkException: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                       Caused by: ru.tinkoff.acquiring.sdk.AcquiringSdkException: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
                                                          at ru.tinkoff.acquiring.sdk.StringKeyCreator.create(StringKeyCreator.java:54)
                                                          at ru.tinkoff.acquiring.sdk.AcquiringSdk.<init>(AcquiringSdk.java:88)
                                                          at ru.tinkoff.acquiring.sdk.AcquiringSdk.<init>(AcquiringSdk.java:81)
                                                          at ru.tinkoff.acquiring.sdk.PayFormActivity.onCreate(PayFormActivity.java:144)
                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                          at android.os.Looper.loop(Looper.java:148) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                       Caused by: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
                                                          at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:250)
                                                          at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:47)
                                                          at java.security.KeyFactory.generatePublic(KeyFactory.java:172)
                                                          at ru.tinkoff.acquiring.sdk.StringKeyCreator.create(StringKeyCreator.java:52)
                                                          at ru.tinkoff.acquiring.sdk.AcquiringSdk.<init>(AcquiringSdk.java:88) 
                                                          at ru.tinkoff.acquiring.sdk.AcquiringSdk.<init>(AcquiringSdk.java:81) 
                                                          at ru.tinkoff.acquiring.sdk.PayFormActivity.onCreate(PayFormActivity.java:144) 
                                                          at android.app.Activity.performCreate(Activity.java:6251) 
                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403) 
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                          at android.os.Looper.loop(Looper.java:148) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                       Caused by: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
                                                          at com.android.org.conscrypt.NativeCrypto.d2i_PUBKEY(Native Method)
                                                          at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:248)
                                                          at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:47) 
                                                          at java.security.KeyFactory.generatePublic(KeyFactory.java:172) 
                                                          at ru.tinkoff.acquiring.sdk.StringKeyCreator.create(StringKeyCreator.java:52) 
                                                          at ru.tinkoff.acquiring.sdk.AcquiringSdk.<init>(AcquiringSdk.java:88) 
                                                          at ru.tinkoff.acquiring.sdk.AcquiringSdk.<init>(AcquiringSdk.java:81) 
                                                          at ru.tinkoff.acquiring.sdk.PayFormActivity.onCreate(PayFormActivity.java:144) 
                                                          at android.app.Activity.performCreate(Activity.java:6251) 
                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403) 
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                          at android.os.Looper.loop(Looper.java:148) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by tralfamadore** [comment]
Сообщил коллегам отвечающим за ЛК, обещают оперативно поправить.

**Comment by SukharevPavel** [comment]
Такая же проблема.

**Comment by domr** [comment]
Проблема решена.
Благодарю.
