### ISSUE TITLE
Terminal not found

### ISSUE THREAD

**Issue by slimmi** [TinkoffCreditSystems/tinkoff-asdk-android#15]
В чем проблема может быть проблема? Данные из магазина скопировал и перепроверил миллион раз.

> Parameters are invalid: Terminal not found. Please check your terminalKey/password
                                                                    ru.tinkoff.acquiring.sdk.AcquiringSdkException: Parameters are invalid: Terminal not found. Please check your terminalKey/password
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:152)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:163)
                                                                        at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:352)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                     Caused by: ru.tinkoff.acquiring.sdk.AcquiringApiException: Parameters are invalid: Terminal not found. Please check your terminalKey/password
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:131)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringApi.init(AcquiringApi.java:69)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:150)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:163) 
                                                                        at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:352) 
                                                                        at java.lang.Thread.run(Thread.java:761) 

Тип подключения: мобильное приложение

**Comment by pantyukhovp** [comment]
Тоже столкнулся с этой проблемой

**Comment by slimmi** [comment]
Частично разобрался с этой проблемой. Данный пакет подразумевает готовое решение. Установил поставил данные из ЛК и поехал, но нет... Какого хера по умолчанию стоит debug = true? И все запросы идут на https://rest-api-test.tinkoff.ru/?

**Comment by slimmi** [comment]
Теперь выдается следующая ошибка:

`Parameters are invalid: token of the request value in not valid
                                                                    ru.tinkoff.acquiring.sdk.AcquiringSdkException: Parameters are invalid: token of the request value in not valid
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.executeInitRequest(AcquiringSdk.java:239)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:111)
                                                                        at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:469)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                     Caused by: ru.tinkoff.acquiring.sdk.AcquiringApiException: Parameters are invalid: token of the request value in not valid
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:150)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringApi.init(AcquiringApi.java:87)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.executeInitRequest(AcquiringSdk.java:237)
                                                                        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:111) 
                                                                        at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:469) 
                                                                        at java.lang.Thread.run(Thread.java:761) `
