### ISSUE TITLE
token of the request value in not valid

### ISSUE THREAD

**Issue by slimmi** [TinkoffCreditSystems/tinkoff-asdk-android#16]
При выполнении запроса выдается следующая ошибка:

> Parameters are invalid: token of the request value in not valid ru.tinkoff.acquiring.sdk.AcquiringSdkException: Parameters are invalid: token of the request value in not valid at ru.tinkoff.acquiring.sdk.AcquiringSdk.executeInitRequest(AcquiringSdk.java:239) at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:111) at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:469) at java.lang.Thread.run(Thread.java:761) Caused by: ru.tinkoff.acquiring.sdk.AcquiringApiException: Parameters are invalid: token of the request value in not valid at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:150) at ru.tinkoff.acquiring.sdk.AcquiringApi.init(AcquiringApi.java:87) at ru.tinkoff.acquiring.sdk.AcquiringSdk.executeInitRequest(AcquiringSdk.java:237) at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:111)  at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:469)  at java.lang.Thread.run(Thread.java:761) 

Данные из ЛК вставлены верно.

**Comment by tralfamadore** [comment]
В какой версии библиотеки возникает ошибка?

**Comment by mechanik0s** [comment]
Подтверждаю проблему, склонировал репозиторий, запустил сэмпл, всё прошло успешно.
Подставил данные тестового терминала из ЛК и при старте активити крашится

> 10-20 14:13:17.006 31581-4902/ru.tinkoff.acquiring.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-5
                                                                            Process: ru.tinkoff.acquiring.sample, PID: 31581
                                                                            ru.tinkoff.acquiring.sdk.AcquiringSdkException: Неверные параметры.: Неверный токен. Проверьте пару TerminalKey/SecretKey.
                                                                                at ru.tinkoff.acquiring.sdk.AcquiringSdk.getCardList(AcquiringSdk.java:155)
                                                                                at ru.tinkoff.acquiring.sdk.CardManager.getCards(CardManager.java:39)
                                                                                at ru.tinkoff.acquiring.sdk.PayFormActivity$1.run(PayFormActivity.java:288)
                                                                                at java.lang.Thread.run(Thread.java:761)
                                                                             Caused by: ru.tinkoff.acquiring.sdk.AcquiringApiException: Неверные параметры.: Неверный токен. Проверьте пару TerminalKey/SecretKey.
                                                                                at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:150)
                                                                                at ru.tinkoff.acquiring.sdk.AcquiringApi.getCardList(AcquiringApi.java:103)
                                                                                at ru.tinkoff.acquiring.sdk.AcquiringSdk.getCardList(AcquiringSdk.java:151)
                                                                                at ru.tinkoff.acquiring.sdk.CardManager.getCards(CardManager.java:39) 
                                                                                at ru.tinkoff.acquiring.sdk.PayFormActivity$1.run(PayFormActivity.java:288) 
                                                                                at java.lang.Thread.run(Thread.java:761)

**Comment by tralfamadore** [comment]
@mechanik0s @slimmi напишите пожалуйста на card_acquiring@tinkoff.ru с указанием данных терминалов, по которым возникает ошибка

**Comment by mechanik0s** [comment]
@tralfamadore отправил

**Comment by mechanik0s** [comment]
@tralfamadore удалось воспроизвести?

**Comment by tralfamadore** [comment]
@mechanik0s Вам должны были ответить с решением.

**Comment by mechanik0s** [comment]
@tralfamadore  увы, это не связано с типом подключения в настройках терминала. Пробовал и универсальное подключение и мобильное.

**Comment by tralfamadore** [comment]
@mechanik0s решилась ли проблема по итогу общения с поддержкой?

**Comment by mechanik0s** [comment]
Моя проблема решилась. Еще бы у автора тикета узнать.

**Comment by tralfamadore** [comment]
@slimmi решилась ли ваша проблема после обращения в поддержку?

**Comment by slimmi** [comment]
@tralfamadore проблему решили следующим образом: отказались от использования SDK, а просто делаем запрос на собственный API сервер, с него запрос на Тиньковские сервера, а после открываем WebView с указанной ссылкой в ответе от Тинковского сервера.

**Comment by slimmi** [comment]
@mechanik0s я могу у себя тоже проверить. Отпишусь.
