### ISSUE TITLE
Ошика поле PAN не может быть пустым

### ISSUE THREAD

**Issue by revers-back** [TinkoffCreditSystems/tinkoff-asdk-android#21]
Подскажите, почему может возникать ошибка 
```
11-09 16:46:38.490 21550-21550/ru.golamago.android.debug E/(StandardErrorHandler.java:67): Unexpected error
                                                                                           ru.tinkoff.acquiring.sdk.AcquiringSdkException: Неверные параметры.: Поле PAN не должно быть пустым.
                                                                                               at ru.tinkoff.acquiring.sdk.AcquiringSdk.finishAuthorize(AcquiringSdk.java:135)
                                                                                               at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:491)
                                                                                               at java.lang.Thread.run(Thread.java:761)
                                                                                            Caused by: ru.tinkoff.acquiring.sdk.AcquiringApiException: Неверные параметры.: Поле PAN не должно быть пустым.
                                                                                               at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:150)
                                                                                               at ru.tinkoff.acquiring.sdk.AcquiringApi.finishAuthorize(AcquiringApi.java:91)
                                                                                               at ru.tinkoff.acquiring.sdk.AcquiringSdk.finishAuthorize(AcquiringSdk.java:133)
                                                                                               at ru.tinkoff.acquiring.sdk.EnterCardFragment$4.run(EnterCardFragment.java:491) 
                                                                                               at java.lang.Thread.run(Thread.java:761) 
```

запуск активити для оплаты происходит так 

` Journal.setDebug(false);
        PayFormActivity
                .init(TinkoffSdkData.TERMINAL_KEY, TinkoffSdkData.PASSWORD, TinkoffSdkData.PUBLIC_KEY)
                .prepare(order.getId(),
                        Money.ofRubles(order.getPrice().getTotal()),
                        getString(R.string.activity_tinkoff_payment_title, order.getNumber()),
                        getString(R.string.activity_tinkoff_payment_message),
                        null,
                        user.getEmail(),
                        false,
                        false
                )
                .setCustomerKey(user.getId())
                .setTheme(R.style.TinkoffTheme)
                .startActivityForResult(this, TinkoffSdkData.TINKOFF_REQUESR_CODE)`

**Comment by Vittt2008** [comment]
1) Скажите какую версию ASDK вы используете, если не последнюю, то обновите до 1.3.2 и посмотрите воспроизводится ли ошибка.
2) Это сообщение об обработанной или необработанной ошибке?
3) Можете ли вы описать шаги по воспроизведению этой ошибки?
4) Воспроизводится ли она, если действительно не ввести номер карты?

**Comment by revers-back** [comment]
1. 1.3.2 нет в maven central. 
Использовали  1.3.1, проблемы была вот в чем "Для типа подключения через мобильный sdk в настройках терминала в Личном кабинете https://oplata.tinkoff.ru необходимо выбрать вкладку «Мобильное приложение» и нажать кнопку «Сохранить»"

Было бы неплохо возвращать человекоподобную ошибку, чтобы не ждать 4 дня ответа тех.поддержки

**Comment by Vittt2008** [comment]
С версией произошла ошибка, последняя действительно 1.3.1.
То есть вы использовали последнюю, все верно.
Что по поводу остальных пунктов?

**Comment by revers-back** [comment]
2.Напрямую SdkApi не используется, запускаем PayFormActivity из своего приложения. Excpetion мы получаем в ru.tinkoff.acquiring.sdk.OnPaymentListener#onError. Сам Exception описан выше. Приложения он не валит, так что обработанное исключение. 
3.шаги с какого момента? запускаем экран оплаты из SDK, параметры перечислены в первом сообщении. 
4. Если не ввести номер карты, экран оплаты выдаст сообщение, что не заполнены требуемые поля

**Comment by MikhailNatalenko** [comment]
Так и что делать с ошибкой в итоге? @Vittt2008
