### ISSUE TITLE
Некорректная работа на honor 8 с Android 7.0

### ISSUE THREAD

**Issue by revers-back** [TinkoffCreditSystems/tinkoff-asdk-android#23]
При открытии экрана оплаты выводится сообщение о невозможности оплаты из-за отсутствия интернета. При этом на самом устройстве доступ в интернет есть и работает коррекнтно. Проблема только на PayFormActivity. 
1. Версия ASDK 1.3.1
2. Модель телефона Honor 8 FDR-09 android 7.0
Остальные данные приведены в конце видео
На видео по ptr происходит перегрузка данных, ошибки доступа интернета нет. При включении режима полета на экране заказа есть ошибка отсутствия интернета как и на PayFormActivity, но она там есть при наличии интернета 
[Видео с шагами воспроизведения бага и детальной информации о телефоне](https://cloud.mail.ru/public/7VSK/EjKhvnxmD
)

**Comment by Vittt2008** [comment]
Включите дебаг режим и пришлите нам логи запросов, так мы ничего не можем сказать.

**Comment by revers-back** [comment]
Сейчас ASDK работает так, что логи для ошибки выше приложить не выйдет. При включении debug режима (Journal.setDebug(true)), происходит другая ошибка, как на данных продового так и  тестового терминала. При этом при Journal.setDebug(false) тестовый и продовый терминалы работают
`01-12 12:55:44.081 13811-13954/com.golamago.store.debug I/System.out: Tinkoff Acquiring SDK: CustomerKey
01-12 12:55:44.081 13811-13954/com.golamago.store.debug I/System.out: Tinkoff Acquiring SDK: Password
01-12 12:55:44.082 13811-13954/com.golamago.store.debug I/System.out: Tinkoff Acquiring SDK: TerminalKey
01-12 12:55:44.090 13811-13954/com.golamago.store.debug I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://rest-api-test.tcsbank.ru/v2/GetCardList
01-12 12:55:44.090 13811-13954/com.golamago.store.debug I/System.out: Tinkoff Acquiring SDK: ===== Parameters: {"CustomerKey":"5d9140ac-30cd-4278-be40-9606bd3312be","TerminalKey":"1507282721861","Token":"{удалил}"}
01-12 12:55:44.142 13811-13947/com.golamago.store.debug E/(EtagInterceptor.java:64): missing etag in response, request url: https://api.golamago.online/orders/ba8a3a17-24b9-4b0c-ac85-10dd423e92a5
01-12 12:55:44.290 13811-13954/com.golamago.store.debug I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Неверный токен. Проверьте пару TerminalKey/SecretKey."}`

**Comment by al-dr** [comment]
Проблема воспроизводится только на указанном устройстве?
Для debug режима вы используете тестовые данные?

**Comment by revers-back** [comment]
1) Проблема с ошибкой отсутствия интернета поймали только на этом устройстве. Стабильно.
2) Пробовал и тестовые данные (демо-терминал) и продовые, результат один и тот же

**Comment by al-dr** [comment]
Мы попробуем найти указанное устройство чтобы воспроизвести описанную ситуацию.
Вы нам сильно поможете, если попробуете вызвать напрямую методы AcquiringApi
init и getCardList, https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/blob/master/core/src/main/java/ru/tinkoff/acquiring/sdk/AcquiringApi.java#L86,
https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/blob/master/core/src/main/java/ru/tinkoff/acquiring/sdk/AcquiringApi.java#L102
методы принимают сущности описывающие запросы, для каждой из них есть соответствующие Builder, 
https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/blob/master/core/src/main/java/ru/tinkoff/acquiring/sdk/requests/InitRequestBuilder.java
https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/blob/master/core/src/main/java/ru/tinkoff/acquiring/sdk/requests/GetCardListRequestBuilder.java
методы могут выбросить  AcquiringApiException, NetworkException. Предполагаю, что речь идет о NetworkException, в нем в логе стэка вызовов предположительно должна быть указана причина.

**Comment by revers-back** [comment]
1. 
`   TinkoffTerminalData data = TinkoffTerminalData.DEMO;
            AcquiringSdk sdk = new AcquiringSdk(data.getTerminalKey(), data.getPassword(), data.getPublicKey());
            Long init = sdk.init(new InitRequestBuilder(data.getPassword(), data.getTerminalKey()));`

Лог ошибки (тут похоже не так как-то InitRequest иницаилизирую)
`01-12 14:39:57.213 16536-16536/com.golamago.store.debug E/(StandardErrorHandler.java:74): Unexpected error
                                                                                          java.lang.IllegalStateException: Unable to build request: field 'Order ID' is null
                                                                                              at ru.tinkoff.acquiring.sdk.requests.AcquiringRequestBuilder.validateNonNull(AcquiringRequestBuilder.java:59)
                                                                                              at ru.tinkoff.acquiring.sdk.requests.AcquiringRequestBuilder.validateNonEmpty(AcquiringRequestBuilder.java:64)
                                                                                              at ru.tinkoff.acquiring.sdk.requests.InitRequestBuilder.validate(InitRequestBuilder.java:151)
                                                                                              at ru.tinkoff.acquiring.sdk.requests.AcquiringRequestBuilder.build(AcquiringRequestBuilder.java:48)
                                                                                              at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:123)
                                                                                              at ru.golamago.android.ui.screen.order.OrderPresenter.lambda$onLoad$9$OrderPresenter(OrderPresenter.java:134)
                                                                                              at ru.golamago.android.ui.screen.order.OrderPresenter$$Lambda$10.call(Unknown Source)
                                                                                              at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
                                                                                              at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
                                                                                              at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                                              at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                                                                                              at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                                                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                              at java.lang.Thread.run(Thread.java:776)`



2. На getCardList уже информативнее

Запрос делается так 
`            TinkoffTerminalData data = TinkoffTerminalData.DEMO;
            AcquiringSdk sdk = new AcquiringSdk(data.getTerminalKey(), data.getPassword(), data.getPublicKey());
            sdk.getCardList(data.getTerminalKey());`

`01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): NetworkErrorHandler handle error
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): ru.tinkoff.acquiring.sdk.AcquiringSdkException: Unable to execute request GetCardList
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at ru.tinkoff.acquiring.sdk.AcquiringSdk.getCardList(AcquiringSdk.java:168)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at ru.golamago.android.ui.screen.order.OrderPresenter.lambda$onLoad$12$OrderPresenter(OrderPresenter.java:145)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at ru.golamago.android.ui.screen.order.OrderPresenter$$Lambda$13.call(Unknown Source)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at rx.Observable.unsafeSubscribe(Observable.java:10256)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at java.lang.Thread.run(Thread.java:776)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): Caused by: ru.tinkoff.acquiring.sdk.NetworkException: Unable to execute request GetCardList
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:168)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at ru.tinkoff.acquiring.sdk.AcquiringApi.getCardList(AcquiringApi.java:115)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at ru.tinkoff.acquiring.sdk.AcquiringSdk.getCardList(AcquiringSdk.java:164)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): 	... 14 more
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.Connection.connectTls(Connection.java:235)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.Connection.connect(Connection.java:172)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
01-12 14:40:01.308 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:157)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): 	... 16 more
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:563)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): 	... 29 more
01-12 14:40:01.309 16536-16536/com.golamago.store.debug I/(NetworkErrorHandler.java:22): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
`

**Comment by al-dr** [comment]
Спасибо за предоставленную информацию, она действительно поможет, решим проблему в ближайшее время.

**Comment by revers-back** [comment]
Верно: Локальное мск, 2017, 12 декабря, вторник 11:54; телефон 2018, 13 января, субббота, 11:55 
Выставил время локальной сети - ошибка не происходит.
