### ISSUE TITLE
Поле PAN не должно быть пустым.

### ISSUE THREAD

**Issue by Zirilla** [TinkoffCreditSystems/tinkoff-asdk-android#42]
Добрый день! Выскакивает ошибка ru.tinkoff.acquiring.sdk.AcquiringApiException: Неверные параметры.: Поле PAN не должно быть пустым.
Используемая версия 1.3.4F
Вызов:
PayFormActivity 
	.init("TERMINAL_KEY", "PASSWORD", "PUBLIC_KEY") 
	.prepare(orderId, 
			Money.ofRubles(orderPrice), 
			title,
			description, 
			null, 
			email, 
			false, 
			true ) 
	.setDesignConfiguration(
                        PayCellType.PRODUCT_TITLE,
                        PayCellType.PRODUCT_DESCRIPTION,
                        PayCellType.AMOUNT,
                        PayCellType.PAYMENT_CARD_REQUISITES,
                        PayCellType.EMPTY_FLEXIBLE_SPACE,
                        PayCellType.PAY_BUTTON,
                        PayCellType.SECURE_LOGOS)
                .startActivityForResult(this, REQUEST_CODE_PAY);

Подскажите пожалуйста в чем дело?

**Comment by al-dr** [comment]
Следует проверить верно ли указан PUBLIC_KEY и проверить настройки терминала

**Comment by Zirilla** [comment]
Проверили настройки, все верно. Ошибка сохраняется. Заметила, что чередуется, один раз говорит, что PAN пустой, другой - ExpDate:
09-03 12:00:29.728 9370-9370/com.lk.telecom.telecomlk E/SAMPLE: Неверные параметры.: Поле ExpDate не должно быть пустым.
    ru.tinkoff.acquiring.sdk.AcquiringSdkException: Неверные параметры.: Поле ExpDate не должно быть пустым.
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.finishAuthorize(AcquiringSdk.java:148)
        at ru.tinkoff.acquiring.sdk.EnterCardFragment$3.run(EnterCardFragment.java:493)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: ru.tinkoff.acquiring.sdk.AcquiringApiException: Неверные параметры.: Поле ExpDate не должно быть пустым.
        at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:182)
        at ru.tinkoff.acquiring.sdk.AcquiringApi.finishAuthorize(AcquiringApi.java:103)
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.finishAuthorize(AcquiringSdk.java:146)
        at ru.tinkoff.acquiring.sdk.EnterCardFragment$3.run(EnterCardFragment.java:493) 
        at java.lang.Thread.run(Thread.java:764) 

Ввожу данные одной и той же карты.

**Comment by Zirilla** [comment]
Больше никаких идей нет по исправлению ошибки???

**Comment by al-dr** [comment]
Следует обратиться в поддержку, (oplata@tinkoff.ru) . Указать ключ терминала, и желательно id не успешного платежа и логи (опция включается  AcquiringSdk#setDebug(boolean))
