### ISSUE TITLE
Ошибка при сканировании карты по NFC

### ISSUE THREAD

**Issue by MariannaVR** [TinkoffCreditSystems/tinkoff-asdk-android#44]
Происходит FATAL EXCEPTION на Android 8.0.0 при попытке сканировать карту по NFC.

```
ru.tinkoff.acquiring.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.tinkoff.acquiring.sample, PID: 26633
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.tinkoff.acquiring.sample/ru.tinkoff.acquiring.sdk.nfc.AsdkNfcScanActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.Activity.onCreate(Activity.java:1038)
        at ru.tinkoff.core.nfc2.BaseNfcActivity.onCreate(BaseNfcActivity.java:22)
        at ru.tinkoff.acquiring.sdk.nfc.AsdkNfcScanActivity.onCreate(AsdkNfcScanActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
```

**Comment by MariannaVR** [comment]
Добрый день!
Проблема решилась, спасибо!
