### ISSUE TITLE
java.lang.IllegalArgumentException: class ru.tinkoff.acquiring.sdk.responses.InitResponse declares multiple JSON fields named serialVersionUID

### ISSUE THREAD

**Issue by dionep** [TinkoffCreditSystems/tinkoff-asdk-android#62]
**При попытке использовать пример я получаю ошибку в logcat:**

```
2019-06-21 01:16:21.735 20917-20917/ru.tinkoff.acquiring.sample E/SAMPLE: class ru.tinkoff.acquiring.sdk.responses.InitResponse declares multiple JSON fields named serialVersionUID
    java.lang.IllegalArgumentException: class ru.tinkoff.acquiring.sdk.responses.InitResponse declares multiple JSON fields named serialVersionUID
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
        at com.google.gson.Gson.getAdapter(Gson.java:458)
        at com.google.gson.Gson.fromJson(Gson.java:926)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:168)
        at ru.tinkoff.acquiring.sdk.AcquiringApi.init(AcquiringApi.java:100)
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.executeInitRequest(AcquiringSdk.java:372)
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:124)
        at ru.tinkoff.acquiring.sdk.EnterCardFragment$5.run(EnterCardFragment.java:739)
        at java.lang.Thread.run(Thread.java:764)
```

**p.s При использовании этой SDK в своём проекте выпинывает с жалобой на проверку Terminalid/secret.**
**Тестовые данные:**
 ```
private static final String DEFAULT_TERMINAL_ID = "dk3DS";
private static final String SDK_TERMINAL_ID = "TestSDK";
private static final String NON_3DS_TERMINAL_ID = "sdkNon3DS";
private static final String PASSWORD = "12345678";
private static final String PUBLIC_KEY = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqBiorLS9OrFPezixO5lSsF+HiZPFQWDO7x8gBJp4m86Wwz7ePNE8ZV4sUAZBqphdqSpXkybM4CJwxdj5R5q9+RHsb1dbMjThTXniwPpJdw4WKqG5/cLDrPGJY9NnPifBhA/MthASzoB+60+jCwkFmf8xEE9rZdoJUc2p9FL4wxKQPOuxCqL2iWOxAO8pxJBAxFojioVu422RWaQvoOMuZzhqUEpxA9T62lN8t3jj9QfHXaL4Ht8kRaa2JlaURtPJB5iBM+4pBDnqObNS5NFcXOxloZX4+M8zXaFh70jqWfiCzjyhaFg3rTPE2ClseOdS7DLwfB2kNP3K0GuPuLzsMwIDAQAB";
```

**Comment by dionep** [comment]
logcat:
2019-08-01 14:05:41.210 24523-24523/com.application E/SAMPLE: Неверные параметры.: Неверный токен. Проверьте пару TerminalKey/SecretKey.
    ru.tinkoff.acquiring.sdk.AcquiringSdkException: Неверные параметры.: Неверный токен. Проверьте пару TerminalKey/SecretKey.
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.executeInitRequest(AcquiringSdk.java:374)
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:124)
        at ru.tinkoff.acquiring.sdk.EnterCardFragment$5.run(EnterCardFragment.java:739)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: ru.tinkoff.acquiring.sdk.AcquiringApiException: Неверные параметры.: Неверный токен. Проверьте пару TerminalKey/SecretKey.
        at ru.tinkoff.acquiring.sdk.AcquiringApi.performRequest(AcquiringApi.java:185)
        at ru.tinkoff.acquiring.sdk.AcquiringApi.init(AcquiringApi.java:100)
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.executeInitRequest(AcquiringSdk.java:372)
        at ru.tinkoff.acquiring.sdk.AcquiringSdk.init(AcquiringSdk.java:124) 
        at ru.tinkoff.acquiring.sdk.EnterCardFragment$5.run(EnterCardFragment.java:739) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by dionep** [comment]
logcat Вашего тестового приложения:
![image](https://user-images.githubusercontent.com/46053683/61453207-3441da00-a966-11e9-8482-d12838fb47df.png)

**Comment by dionep** [comment]
Какой именно json вы хотите увидеть?

**Comment by dionep** [comment]
Ваше тестовое приложение:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46053683/61625243-e6d5ad80-ac82-11e9-9b0a-a5fd896751c6.gif)
