### ISSUE TITLE
Запуск простейшего примера на C#. GATEWAY_REQUEST_DATA_ERROR: Invalid token scopes.

### ISSUE THREAD

**Issue by Casper-SC** [TinkoffCreditSystems/tinkoff-asdk-android#74]
Здравствуйте. Всё сделал по инструкции, запускаю приложение и вижу ошибку: 

> Tinkoff.Trading.OpenApi.Network.OpenApiException: GATEWAY_REQUEST_DATA_ERROR: Invalid token scopes (c8de689d4a5e2b60).
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path)
>    at Tinkoff.Trading.OpenApi.Network.Context.AccountsAsync()
>    at TinkoffTradingRobot.Program.Run(String[] args) in F:\Programming\C#\WORK\TinkoffTradingRobot\TinkoffTradingRobot\Program.cs:line 31

Что с этим делать непонятно совершенно. Ваш же API, ваш же код, не работает.

```
using System;
using System.Threading.Tasks;
using Tinkoff.Trading.OpenApi.Network;

namespace TinkoffTradingRobot
{
    class Program
    {
        private static Program _program;

        private static Task Main(string[] args)
        {
            _program = new Program();
            return _program.Run(args);
        }

        private async Task Run(string[] args)
        {
            // токен аутентификации
            string token = "Токен сгенерировал по инстукции. Это Sandbox.";

            // для работы в песочнице используйте GetSandboxConnection
            var connection = ConnectionFactory.GetConnection(token);
            using var context = connection.Context;
            try
            {
                // вся работа происходит асинхронно через объект контекста
                var portfolio = await context.PortfolioAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.ReadKey();
        }
    }
}
```

**Comment by Casper-SC** [comment]
Удалил из токена в начале "t.". Новая ошибка:

> Tinkoff.Trading.OpenApi.Network.OpenApiException: Access Denied: You have no access to that resource..
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path)
>    at Tinkoff.Trading.OpenApi.Network.Context.PortfolioAsync(String brokerAccountId)
>    at TinkoffTradingRobot.Program.Run(String[] args) in F:\Programming\C#\WORK\TinkoffTradingRobot\TinkoffTradingRobot\Program.cs:line 32

**Comment by Casper-SC** [comment]
Тема переехала в [раздел C#](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/issues/48). Сюда я попал по ссылке, не обратил внимание, что это про Android.
