### ISSUE TITLE
NullPointerException в EnterCardFragment

### ISSUE THREAD

**Issue by punksta** [TinkoffCreditSystems/tinkoff-asdk-android#8]
версия сдк 'ru.tinkoff.acquiring:ui:1.1.1'
лог из фабрика
Galaxy Tab3 8.0, android 4.4.2
```
Fatal Exception: java.lang.NullPointerException
       at ru.tinkoff.acquiring.sdk.EnterCardFragment$5.run(EnterCardFragment.java:385)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tralfamadore** [comment]
Исправлено в 1.2.0
